set nocompatible
set background=dark

if !has('win32') && !has('win64')
  set term=$TERM
endif

filetype off
filetype plugin indent off
" set rtp+=~/.vim/bundle/vundle/
" call vundle#rc()

filetype plugin indent on
syntax on

set mouse-=a

scriptencoding utf-8

set history=1000

" Search
set showmatch
set hlsearch
set ignorecase
set smartcase

" Spacing and Tabs
set ts=2 sts=2 sw=2
set expandtab
set nowrap
set autoindent
set preserveindent

set scrolloff=8

" Appearance
set nonumber
set nowrap
set linebreak
set list listchars=trail:~
" set columns=80
set showmode
set modelines=1

cmap W  w
cmap Wq wq

" When you forget to sudo...
cmap w!! w !sudo tee % >/dev/null

nnoremap <CR> :noh<CR><CR>:<backspace>

" Bundles
" Bundle 'gmarik/vundle'
